import type { ReactNode } from "react"

import type { AquaDocumentDensity, AquaProductTheme } from "../design-system"
import { aquaTechCsTheme } from "../design-system"

import AquaMark from "./AquaMark"

type AquaSystemDocumentProps = {
  title: string
  documentLabel: string
  children: ReactNode
  reference?: string
  issuedAt?: string
  density?: AquaDocumentDensity
  footerNote?: string
  theme?: AquaProductTheme
}

export default function AquaSystemDocument({
  title,
  documentLabel,
  children,
  reference,
  issuedAt,
  density = "comfortable",
  footerNote,
  theme = aquaTechCsTheme,
}: AquaSystemDocumentProps) {
  const resolvedFooterNote = footerNote ?? `Generated by ${theme.productName}`

  return (
    <article
      className="aqua-system-document"
      data-aqua-density={density}
      aria-labelledby="aqua-system-document-title"
    >
      <header className="aqua-system-document__header">
        <div className="aqua-system-document__brand">
          <AquaMark showText={false} size="sm" theme={theme} />
          <div>
            <strong>{theme.companyName}</strong>
            <span>{theme.productName}</span>
          </div>
        </div>

        <div className="aqua-system-document__meta">
          <strong>{documentLabel}</strong>
          {reference ? <span dir="ltr">{reference}</span> : null}
          {issuedAt ? <span dir="ltr">{issuedAt}</span> : null}
        </div>
      </header>

      <h1 id="aqua-system-document-title" className="aqua-system-document__title">
        {title}
      </h1>

      <div className="aqua-system-document__body">{children}</div>

      <footer className="aqua-system-document__footer">
        <span>{resolvedFooterNote}</span>
        <span dir="ltr">
          {theme.companyName} © {theme.productName}
        </span>
      </footer>
    </article>
  )
}

export type { AquaSystemDocumentProps }
