import type { ReactNode } from "react"

import type { AquaDocumentDensity } from "@/design-system"
import { aquaBrand } from "@/lib/brand"

import AquaMark from "./AquaMark"

type AquaSystemDocumentProps = {
  title: string
  documentLabel: string
  children: ReactNode
  reference?: string
  issuedAt?: string
  density?: AquaDocumentDensity
  footerNote?: string
}

export default function AquaSystemDocument({
  title,
  documentLabel,
  children,
  reference,
  issuedAt,
  density = "comfortable",
  footerNote = "Generated by AquaFlow",
}: AquaSystemDocumentProps) {
  return (
    <article
      className="aqua-system-document"
      data-aqua-density={density}
      aria-labelledby="aqua-system-document-title"
    >
      <header className="aqua-system-document__header">
        <div className="aqua-system-document__brand">
          <AquaMark showText={false} size="sm" />
          <div>
            <strong>{aquaBrand.name}</strong>
            <span>{aquaBrand.product}</span>
          </div>
        </div>

        <div className="aqua-system-document__meta">
          <strong>{documentLabel}</strong>
          {reference ? <span dir="ltr">{reference}</span> : null}
          {issuedAt ? <span dir="ltr">{issuedAt}</span> : null}
        </div>
      </header>

      <h1 id="aqua-system-document-title" className="aqua-system-document__title">
        {title}
      </h1>

      <div className="aqua-system-document__body">{children}</div>

      <footer className="aqua-system-document__footer">
        <span>{footerNote}</span>
        <span dir="ltr">Aqua.Tech © AquaFlow</span>
      </footer>
    </article>
  )
}

export type { AquaSystemDocumentProps }
